name: Deploy ADAudit Tool to Dev

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: arc-runner-dind

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files to dev server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: ${{ secrets.DEV_PORT }}
          source: "."
          target: "/srv/docker/stacks/dev-apps/adaudit"
          strip_components: 0
          rm: false

      - name: Deploy web only
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: ${{ secrets.DEV_PORT }}
          script: |
            cd /srv/docker/stacks/dev-apps/adaudit
            docker compose -f docker-compose.dev.yml up -d --build --no-deps adaudit-web
